# Generated by Django 3.0.6 on 2020-05-24 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignedto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completedby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('InP', 'Inprogress'), ('D', 'Done'), ('InV', 'Invalid')], default='N', max_length=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketfiler',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticketfiler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
